FROM node:8.11.4 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i
COPY . .

RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /usr/src/app/dist/eSchool .

ENV BACKEND_URL=BACKEND_URL
COPY entry.sh /conf/entry.sh
RUN chmod +x /conf/entry.sh
ENTRYPOINT ["/conf/entry.sh"]
CMD ["nginx", "-g", "daemon off;"]

